### ISSUE TITLE
f28: no such container

### ISSUE THREAD

**Issue by ikke-t** [jdoss/unifi#1]
Hi, I tried to follow your instructions on Fedora 28. Both from github and locally the build fails:

```
$ sudo podman build --build-arg UNIFI_VERSION=5.8.23-d5a5bbfda4     --build-arg UNIFI_UID=$(id -u unifi)     -t unifi:5.8.23-d5a5bbfda4 git://github.com/jdoss/unifi
could not get runtime: error retrieving temporary directory for container 99f6bac70767cd4bd84e186625e0134e5c0b6626757923151b0e2eb67f57576e: no such container
```

I have also docker on my machine, I stopped that one and still same result. Some piece of a puzzle missing form instructions. Could be some missing directory from podman.

**Comment by jdoss** [comment]
That is an odd error. I just followed the build from GitHub instructions on a fresh Fedora 28 install and I didn't get that error. Podman tries to store the context it pulls down form GitHub in a temporary location. Maybe that location isn't writable on your machine? Can you try the [build locally](https://github.com/jdoss/unifi#build-locally) instructions and see if you get the same error?
